services:
  backend:
    restart: unless-stopped
    build: ./src-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - static:/www/static
      - media:/www/media
    depends_on:
      - mongodb
    networks:
      - jf_net

  frontend:
    restart: unless-stopped
    build: ./src-frontend
    ports:
      - "3000:3000"
    volumes:
      - static:/www/static
      - media:/www/media
    depends_on:
      - backend
    networks:
      - jf_net

  mongodb:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arunmongo
      - MONGO_INITDB_ROOT_PASSWORD=arunrocks
    networks:
      - jf_net

  nginx:
    restart: unless-stopped
    env_file:
      - .env
    container_name: nginx
    build:
      context: ./src-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - static:/www/static
      - media:/www/media
    networks:
      - jf_net

volumes:
  static:
  media:


networks:
  jf_net:
